# Generated by Django 5.0.1 on 2024-03-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=200)),
                ('Saddress', models.CharField(max_length=200)),
                ('Scode', models.IntegerField()),
            ],
        ),
    ]
